language: java
jdk:
   -openjdk8


addons:
  sonarcloud:
    organization: "ariannafreda12"
    token:
      secure: "af78d16da9f0854856b7b02390c01c5984cbab9e" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner