dist: trusty
language: java
jdk:
   -openjdk8


addons:
 sonarcloud:
  organization: "ariannafreda12"
  token: "travis encrypt ea925d60e24786ee13ecebcdd75383f5fb867f14"
script:
-ant build
-sonar-scanner
